name = "yajna-auth"
main = "src/index.js"
compatibility_date = "2024-04-26"

[vars]
# ALLOWED_ORIGIN = "https://theitush.github.io" # Overridden by secret in production

# Secrets:
# GOOGLE_CLIENT_ID
# GOOGLE_CLIENT_SECRET
# TOKEN_ENCRYPTION_KEY
# ALLOWED_ORIGIN
